apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kuadrant-operator
  namespace: kuadrant-system
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: kuadrant-operator
  source: operatorhubio-catalog
  sourceNamespace: olm
  config:
    env: 
      - name: ISTIOOPERATOR_NAME
        value: {{.IstioOperator}}  
      - name: ISTIOCONFIGMAP_NAME
        value: {{.IstioConfigMapName}}
      - name: ISTIOOPERATOR_NAMESPACE
        value: {{.IstioOperatorNamespace}}
   