# Resources to be created in the tenant namespace in the control plane

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- role.yaml
- rolebinding.yaml
- serviceaccount.yaml

namespace: tenant
