apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: syncer
  namespace: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: syncer
subjects:
- kind: ServiceAccount
  name: syncer
  namespace: system
