apiVersion: v1
kind: ServiceAccount
metadata:
  name: syncer
  namespace: system
---
apiVersion: v1
kind: Secret
metadata:
  name: syncer-token
  namespace: system
  annotations:
    kubernetes.io/service-account.name: syncer
type: kubernetes.io/service-account-token  