# Local deployment overlay.
#
# This requires the following .env files to exist in the project directory before
# it can be used:
# controller-config.env
# aws-credentials.env

resources:
  - ../../default

namespace: multicluster-gateway-controller-system

generatorOptions:
  disableNameSuffixHash: true

patchesStrategicMerge:
- manager_config_patch.yaml