apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: kuadrant-multi-cluster-gateway-instance-per-cluster
spec:
  controllerName: "kuadrant.io/mgc-gw-controller"
  parametersRef:
    group: ""
    kind: "ConfigMap"
    namespace: "multi-cluster-gateways"
    name: "gateway-params"
