apiVersion: kuadrant.io/v1alpha1
kind: DNSRecord
metadata:
  labels:
    app.kubernetes.io/name: dnsrecord-geo
    app.kubernetes.io/instance: dnsrecord-sample
    app.kubernetes.io/part-of: multicluster-gateway-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: multicluster-gateway-controller
  name: dnsrecord-geo
spec:
  managedZone:
    name: mgc-dev-mz
  endpoints:
    - dnsName: dnsrecord-geo.mn.hcpapps.net
      recordTTL: 60
      recordType: CNAME
      setIdentifier: Default
      providerSpecific:
        - name: "aws/geolocation-country-code"
          value: "*"
      labels:
        id: Default
      targets:
        - dnsrecord-geo.na.mn.hcpapps.net
    - dnsName: dnsrecord-geo.mn.hcpapps.net
      recordTTL: 60
      recordType: CNAME
      setIdentifier: NA
      providerSpecific:
        - name: "aws/geolocation-continent-code"
          value: "NA"
      labels:
        id: NA
      targets:
        - dnsrecord-geo.na.mn.hcpapps.net
    - dnsName: dnsrecord-geo.na.mn.hcpapps.net
      recordTTL: 60
      recordType: A
      setIdentifier: 50.16.23.1
      providerSpecific:
        - name: "weight"
          value: "60"
      labels:
        id: 50.16.23.1
      targets:
        - 50.16.23.1
    - dnsName: dnsrecord-geo.na.mn.hcpapps.net
      recordTTL: 60
      recordType: A
      setIdentifier: 50.16.23.2
      providerSpecific:
        - name: "weight"
          value: "60"
      labels:
        id: 50.16.23.2
      targets:
        - 50.16.23.2
