apiVersion: v1
kind: Namespace
metadata:
  name: mctc-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sync-agent
  namespace: mctc-system
spec:
  selector:
    matchLabels:
      control-plane: sync-agent
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: sync-agent
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /agent
        args:
        - --leader-elect
        - -control-plane-config-namespace=mctc-system
        image: agent:latest
        imagePullPolicy: Never
        name: agent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: sync-agent
      terminationGracePeriodSeconds: 10