apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: webhook-proxy
    app.kubernetes.io/name: namespace
    app.kubernetes.io/created-by: multi-cluster-traffic-controller
    app.kubernetes.io/part-of: multi-cluster-traffic-controller
    app.kubernetes.io/managed-by: kustomize
  name: system