apiVersion: apps/v1
kind: Deployment
metadata:
  name: sync-agent
  namespace: mgc-system
spec:
  selector:
    matchLabels:
      control-plane: sync-agent
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: sync-agent
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /syncer
        args:
        - -control-plane-config-namespace=mgc-system
        - -control-plane-config-name=control-plane-cluster-internal
        - -synced-resources=gateways.v1beta1.gateway.networking.k8s.io
        - -synced-resources=secrets.v1
        env:
          - name: DATAPLANE_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        image: syncer:latest
        imagePullPolicy: Never
        name: syncer
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: sync-agent
      terminationGracePeriodSeconds: 10
