apiVersion: kuadrant.io/v1beta1
kind: RateLimitPolicy
metadata:
  name: echo-rlp
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: example-gateway
  rateLimits:
    - rules:
      - hosts: [ "myapp.mn.hcpapps.net" ]
      limits:
        - conditions:
            - 'kuadrant_gateway_cluster == "mctc-workload-1"'
          maxValue: 1
          seconds: 10
