apiVersion: kuadrant.io/v1beta1
kind: RateLimitPolicy
metadata:
  name: echo-rlp
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: example-gateway
  rateLimits:
    - rules:
      - hosts: [ "myapp.mn.hcpapps.net" ]
      limits:
        - conditions:
            - 'cloud == "aws"'
          maxValue: 2
          seconds: 10
        - conditions:
            - 'cloud == "gcp"'
          maxValue: 8
          seconds: 10
